export const environment = {
  production: true,
  apiBaseUrl: 'http://localhost:8080/api/v1',
  labsEndpointPath: '/labs',
  staffEndpointPath: '/staff',
  productsEndpointPath: '/products',
  rawMaterialsEndpointPath: '/raw-materials',
  equipmentEndpointPath: '/equipment',
  bpmConfigEndpointPath: '/bpm-config',
  maintenanceEndpointPath: '/maintenance',
  telemetryEndpointPath: '/telemetry',
  deviceBindingsEndpointPath: '/device-bindings',
  complianceEndpointPath: '/compliance',
  alertsEndpointPath: '/alerts',
  notificationPrefsEndpointPath: '/notification-preferences',
  batchesEndpointPath: '/batches',
  rawMaterialUsageEndpointPath: '/raw-material-usages',
  reportsEndpointPath: '/reports',
  kpisEndpointPath: '/kpis',
  auditLogEndpointPath: '/audit-log',
  deviationTrendsEndpointPath: '/deviation-trends',
  signInEndpointPath: '/auth/sign-in',
  signUpEndpointPath: '/auth/sign-up',
  recoverPasswordEndpointPath: '/auth/recover-password',
};
